spring:
  datasource:
    url: jdbc:postgresql://${HOST_NAME}:5432/?user=${DB_USERNAME}&password=${DB_PASSWORD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kakao:
    auth:
      client-id: ${KAKAO_CLIENT_ID}
      redirect-uri: ${KAKAO_REDIRECT_URL}

  jwt:
    secret: ${JWT_SECRET_CODE}

cloud:
  aws:
    s3:
      bucket: pinggu-s3
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: us-east-1
    stack:
      auto: false

server:
  address: 0.0.0.0
  port: 8080